### ISSUE TITLE
  Attempt to read property "model_parando" on null when generateing brevet card outside (single blank)

### ISSUE THREAD

**Issue by smkeesle** [ctnadovich/randowizard#12]
When I clicked "brevet card outside (single blank)" from 
https://randonneuring.org/index.php/route_manager/932007-62
I received the following:

Exception
Libraries/Brevetcard.php(390)

Attempt to read property "model_parando" on null
Backtrace

/var/www/html/randonneuring.org/ci/app/Controllers/BaseController.php:156 App\Controllers\BaseController::die_message()
/var/www/html/randonneuring.org/ci/app/Controllers/Generate.php:76 App\Controllers\BaseController::die_exception()
/var/www/html/randonneuring.org/ci/vendor/codeigniter4/framework/system/CodeIgniter.php:934 App\Controllers\Generate::generate()
/var/www/html/randonneuring.org/ci/vendor/codeigniter4/framework/system/CodeIgniter.php:499 CodeIgniter\CodeIgniter::runController()
/var/www/html/randonneuring.org/ci/vendor/codeigniter4/framework/system/CodeIgniter.php:368 CodeIgniter\CodeIgniter::handleRequest()
/var/www/html/randonneuring.org/ci/public/index.php:67 CodeIgniter\CodeIgniter::run()

**Comment by smkeesle** [comment]
This is a new route I entered. It isn't published yet, so there are no riders.

**Comment by ctnadovich** [comment]
Fixed
