### ISSUE TITLE
CSV Cue Sheet has no cues

### ISSUE THREAD

**Issue by smkeesle** [ctnadovich/randowizard#13]
When I generate a csv cuesheet from:
https://randonneuring.org/index.php/route_manager/932007-62
(a new, unpublished route)
The file contains the following:

Event:,"Letchworth-Cayuga 600K"
"Event Start Date/Time:"," 2024-07-13 06:30 EDT"
"Official Distance:"," 600 km"
"Event Type:",ACP
Distance:," 373 mi / 600.3 km"
Climbing:," 17483 ft"
Organizer:," Sean Keesler (607-227-0276)"
"RWGPS Name:"," Letchworth-Cayuga 600k  (FL Forest)"
Modified:," 2023-11-13 22:58:59 EST"
"Cues Generated:"," 2023-11-13 23:16 EST"
"Cuesheet Version:"," None"

...but none of the directional cues.

**Comment by ctnadovich** [comment]
Fixed
